# Values for Tenant B

projectId: "phrasal-method-417611"
region: "<REGION>"

appConfig:
  dbInstance: "Tenant B DB"
  dbInstanceName: "mssql-tenant-b"
  secretKey: "tenant-b-db-password"

serviceAccount:
  gcpServiceAccount: "tenant-b-app-sa@<PROJECT_ID>.iam.gserviceaccount.com"
