# Default values for gke-demo-app.

replicaCount: 2

image:
  repository: europe-west4-docker.pkg.dev/phrasal-method-417611/my-app-repo/my-app
  tag: v1.0
  pullPolicy: IfNotPresent

# GCP Project and Region
projectId: "phrasal-method-417611"
region: "<REGION>"

# Application Configuration
appConfig:
  dbInstance: "Default DB"
  dbInstanceName: "mssql-default"
  secretKey: "tenant-default-db-password"

# Service Configuration
service:
  type: LoadBalancer
  port: 80

# Service Account Configuration
serviceAccount:
  create: true
  name: ""
  gcpServiceAccount: "" # To be filled in tenant values
