apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gke-demo-app.fullname" . }}
  labels:
    {{- include "gke-demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gke-demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gke-demo-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gke-demo-app.serviceAccountName" . }}
      containers:
      - name: app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DB_INSTANCE
          valueFrom:
            configMapKeyRef:
              name: {{ include "gke-demo-app.fullname" . }}-config
              key: db_instance
        - name: CONNECTION_STRING
          value: "Server=127.0.0.1;Database=TransactionsDB;User Id=sqlserver;Password=$(DB_PASSWORD);TrustServerCertificate=True;"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password-secret
              key: password

      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.2
        args:
        - "--port=1433"
        - "$(INSTANCE_CONNECTION_NAME)"
        env:
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "gke-demo-app.fullname" . }}-config
              key: connection_name
        securityContext:
          runAsNonRoot: true
