apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "gke-demo-app.fullname" . }}-store
  labels:
    {{- include "gke-demo-app.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectId | quote }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password-secret
  labels:
    {{- include "gke-demo-app.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "gke-demo-app.fullname" . }}-store
    kind: SecretStore
  target:
    name: db-password-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.appConfig.secretKey | quote }}
